// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6yVgFsN_D2KJ2v9ejKd0Xj5p6GgsxVi4',
    appId: '1:1076134014363:web:f5f992babfe0f56aa7853e',
    messagingSenderId: '1076134014363',
    projectId: 'nexum-backend',
    authDomain: 'nexum-backend.firebaseapp.com',
    storageBucket: 'nexum-backend.appspot.com',
    measurementId: 'G-V652ZVGT9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMJE5r1Ca3jfpcoGF7-10SZ_8v6OzGlG8',
    appId: '1:1076134014363:android:b3873fda113f6e44a7853e',
    messagingSenderId: '1076134014363',
    projectId: 'nexum-backend',
    storageBucket: 'nexum-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcw1k2J7ZFx_lV59wow7biKB53m6_c7UU',
    appId: '1:1076134014363:ios:342d10b845570a00a7853e',
    messagingSenderId: '1076134014363',
    projectId: 'nexum-backend',
    storageBucket: 'nexum-backend.appspot.com',
    iosBundleId: 'com.nexumconnects.ios',
  );
}
